### ISSUE TITLE
createdAt and updatedAt 

### ISSUE THREAD

**Issue by kimmobrunfeldt** [Vincit/moron.js#20]
What would be the most appropriate method to place code which updates `createdAt` and `updatedAt` columns ?

**Comment by juanjoLenero** [comment]
You could handle that through the knex table definition, here's an example of one of my migrations:
```javascript
exports.up = function (knex) {
    return knex.schema
        .createTable('Users', function (table) {
            table.bigincrements('id').primary();
            table.string('email').notNullable();
            table.string('password');
            table.timestamp('createdAt').defaultTo(knex.raw('now()'));
            table.timestamp('updatedAt').defaultTo(knex.raw('now()'));
        })
        //...
```
I haven't done extensive testing to make sure this works in all cases, but it has worked well so far.

I'm using postgres by the way, not sure if the `now()` function exists in other dbms.

**Comment by kimmobrunfeldt** [comment]
Ok. Thanks for that workaround. One downside is that now() depends on the underlying database:

> Note that the method for defaulting to the current datetime varies from one database to another. For example: PostreSQL requires .defaultTo(knex.raw('now()')), but SQLite3 requires .defaultTo(knex.raw("date('now')")).

**Comment by kimmobrunfeldt** [comment]
@juanjoLenero In your example, how is updatedAt different from createdAt? If you update the updatedAt column manually at some place, where are you doing it?

**Comment by juanjoLenero** [comment]
It's not different, I haven't gotten around to fixing it. The orm's I have used in the past all handled it by themselves. I will probably add a trigger to my tables so the updatedAt timestamp is refreshed after each update.

**Comment by kimmobrunfeldt** [comment]
Ok. I'd prefer to have this behavior app side, not with database triggers.

**Comment by koskimas** [comment]
It should be pretty easy to add a support in the app side for those. I'll look into it. What kind of API would you like? Would something like this work for you:

```js
Person.timeStampColumns = {
  create: 'createdAt',
  update: 'updatedAt'
};
```

By default the timestamps would be disabled.

**Comment by kimmobrunfeldt** [comment]
Those are very common columns to have so something like that would work. On the other hand mire generic API could be useful in other features. By more generic I mean something like $beforeSave method which could update these timestamps.

**Comment by koskimas** [comment]
I'd also prefer something more generic. `$before` hooks are an excellent idea! I dont know why I haven't added them already :D.  I'll add `$beforeInsert` and `$beforeUpdate` hooks? Does that sound good?

**Comment by elhigu** [comment]
Sounds good idea to have before insert / update. 

@kimmobrunfeldt I would prefer doing these with triggers, since they will work, even when rows are updated e.g. directly with knex queries, but I do also agree that having updates on app-side has also its benefits. 

Would be great to have Cookbook examples of both, db trigger and `$beforeXXXX` ways to do this.

**Comment by juanjoLenero** [comment]
Hooks sound great, I was experimenting with AOP through [advice] (https://github.com/dataminr/advice) to try and get that functionality since I've some uses cases for them. After insert/update hooks would also be useful.

**Comment by koskimas** [comment]
I'll also add `$afterInsert` and `$afterUpdate`. Are synchronous methods enough or should it be possible to return a `Promise` from the hooks so that you can do async stuff?

**Comment by kimmobrunfeldt** [comment]
In my case the call is synchronous but If it fits the rest of API to use promises, I would go with that. You can always achieve synchronous with Promises but not the other way.

**Comment by koskimas** [comment]
I [added simple synchronous hooks](https://github.com/Vincit/moron.js/commit/c04bdbaaca54e37695d552dec90661a698cb3523) for now. They can be made asynchronous without breaking backward compatibility if someone needs such feature later.
