### ISSUE TITLE
How to automatically convert camelCase Javascript fields to snake-case database columns in all models?

### ISSUE THREAD

**Issue by moroshko** [Vincit/moron.js#22]
First of all, thanks for a great library!

I wonder whether there is a way to automatically convert **all** camelCase Javascript fields to snake-case database columns. I'd like to apply [this trick](https://github.com/Vincit/moron.js/blob/master/RECIPES.md#map-column-names-to-different-property-names) to all models, rather than to every individual model.

Is that possible?

**Comment by koskimas** [comment]
You can create a new base class for all your models that does the trick. Currently there is no easier way. So just create something like:

```js
function MyModelBase() {
  Model.apply(this, arguments);
}

Model.extend(MyModelBase);
module.exports = MyModelBase;

MyModelBase.prototype.$formatDatabaseJson = function (json) {
  json = Model.prototype.$formatDatabaseJson.call(this, json);

  return _.mapKeys(json, function (value, key) {
    return _.snakeCase(key);
  });
};

MyModelBase.prototype.$parseDatabaseJson = function (json) {
  json = _.mapKeys(json, function (value, key) {
    return _.camelCase(key);
  });

  return Model.prototype.$parseDatabaseJson.call(this, json);
};
```

and then inherit all your models from that class instead of `moron.Model`.

**Comment by moroshko** [comment]
@koskimas Thanks for a quick reply!

How would this look in es7?

**Comment by koskimas** [comment]
The `MoronModel` is fully compatible with ES6 classes. You should be able to use normal inheritance:

```js
import {Model} from 'moron';

export default class MyModelBase extends Model {
  $formatDatabaseJson(json) {
    json = super.$formatDatabaseJson(json);

    return _.mapKeys(json, function (value, key) {
      return _.snakeCase(key);
    });
  }

  $parseDatabaseJson(json) {
    json = _.mapKeys(json, function (value, key) {
      return _.camelCase(key);
    });

    return super.$parseDatabaseJson(json);
  }
}
```

**Comment by moroshko** [comment]
Cheers!
