### ISSUE TITLE
Add to README : how to connect to the database.

### ISSUE THREAD

**Issue by Thebigbignooby** [Vincit/moron.js#26]
I seem to understand that one should use knex to connect to the database, but then how do we use knex in relation to moron.js?

I must be a moron, but I'd like simple easy-to-follow instructions for setting up a connection to the database and using it with moron.js before showing how to use the models.

**Comment by koskimas** [comment]
Did you look at the example project? It has a simple app.js that binds all the needed stuff together including knex initialization. Maybe I should add the instructions to README also though.

**Comment by Thebigbignooby** [comment]
Yes I finally figured it out after going back and forth between the files in the example project.
but yes adding it to the README would be great! : explain that one needs knex to connect and then show an example of how to do it :+1:
