### ISSUE TITLE
Estimated to support SQL Server 

### ISSUE THREAD

**Issue by brunoksato** [Vincit/moron.js#7]
you have estimated SQL Server ? 

Thanks !

**Comment by koskimas** [comment]
moron.js only supports the databases knex supports and SQL Server isn't one of them.

**Comment by brunoksato** [comment]
If you add tedious in project ? have big problem ?

**Comment by koskimas** [comment]
As soon as that PR is merged to knex, moron.js can support mssql. I don't want to fork knex.

**Comment by goldpot** [comment]
@mceachen  so we have support for MSSQL now using knex or objection.js?

**Comment by jcwatson11** [comment]
Just want to bump this issue and see if we can get confirmation that SQL Server is supported now in Objection.js because knex added support for the tedious driver.

Can you confirm this?

**Comment by devinivy** [comment]
I've used objection v2 with SQL Server, and it's worked great.

**Comment by jcwatson11** [comment]
Great! Thanks!

**Comment by jcwatson11** [comment]
Might want to change the docs to reflect that too. Not sure how or who would do that.

**Comment by ralphskie** [comment]
okay, so how did you do it? care to share?

checking it here  :  https://vincit.github.io/objection.js/guide/?
no sql package on the doc, wanting to know what package you use.

**Comment by KrisLau** [comment]
@ralphskie I'm moving over my database from `postgres` to `mssql`. Did you have to change any of the queries that you had previously used?
