### ISSUE TITLE
Arrow syntax es6

### ISSUE THREAD

**Issue by brunoksato** [Vincit/moron.js#8]
Example current: 

     Person
      .query()
      .where('age', '>', 40)
      .andWhere('age', '<', 60)
      .andWhere('firstName', 'Jennifer')
      .orderBy('lastName')
      .then(function (middleAgedJennifers) {
        console.log('The last name of the first middle aged Jennifer is');
        console.log(middleAgedJennifers[0].lastName);
      });

Example style ES6 Arrow :

    Person
      .query()
      .where(x => x.age > 40)
      .andWhere(x => x.age < 60)
      .andWhere(x => x.firstName == 'Jennifer')
      .orderBy(x => x.lastName)
      .then(function (middleAgedJennifers) {
        console.log('The last name of the first middle aged Jennifer is');
        console.log(middleAgedJennifers[0].lastName);
      });

this syntax is wonderful.

**Comment by koskimas** [comment]
Yes, this syntax would be great but it's impossible to implement. We should run the arrow "lambdas" in the database or get some kind of "exrpression object" as a return value. Neither of these can be implemented with javascript and relational databases.

**Comment by brunoksato** [comment]
could not possibly create a parse ?

**Comment by koskimas** [comment]
Well if you give the expressions as strings like `.where('x => x.age > 40')` it would be possible, but then why wouldn't we just write  `.where('age > 40')`. Anyways I don't think this is a good idea.
